"""fix

Revision ID: 405c3a7712ce
Revises: 9475c09adea0
Create Date: 2025-08-20 23:56:41.783420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405c3a7712ce'
down_revision = '9475c09adea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_savings_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_savings_user_id'))

    # ### end Alembic commands ###
