"""savings log and other

Revision ID: 9475c09adea0
Revises: 67a21c9acaae
Create Date: 2025-08-20 23:24:49.971271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9475c09adea0'
down_revision = '67a21c9acaae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savings_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('savings_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount >= 0', name='savings_log_positive'),
    sa.ForeignKeyConstraint(['savings_id'], ['savings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('savings_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_savings_log_savings_id'), ['savings_id'], unique=False)

    with op.batch_alter_table('savings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_savings_user_id'))
        batch_op.create_index(batch_op.f('ix_savings_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_savings_user_id'))
        batch_op.create_index(batch_op.f('ix_savings_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('savings_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_savings_log_savings_id'))

    op.drop_table('savings_log')
    # ### end Alembic commands ###
